First, we import numpy as np.  In the past, we've been able to import modules directly.  Although we can do that with numpy (and other modules) we don't.  Why not?  The more modules we import into the <font color="red">global namespace</font>, the more opportunity we have for <font color="red">namespace collision</font>.  That's what happens when two modules try to use the same variable names.  One will get overwritten, and then something will likely break!

In [2]:
import numpy as np

Perhaps the most simple thing we can do is cast lists as numpy arrays.  This is a single dimensional array.

In [3]:
# Here, we're using a numpy method called "array".  
# We're passing it an ordinary python list, but 
# it is turning it into a numpy array.

x = np.array([1,5,3,7,9])
x

array([1, 5, 3, 7, 9])

In [ ]:
# Play along!  Create 3 numpy arrays using np.array.

In [77]:
l = [5,6,9,3,"red"]
np.array(l)

array(['5', '6', '9', '3', 'red'], 
      dtype='<U11')

This is a two dimensional array, created using a list of lists.  Imagine this as a 2x2 square, or raster.

In [4]:
x = np.array([[4,5],[9,8]])
x

array([[4, 5],
       [9, 8]])

In [ ]:
# Play along!  Create 3 two dimensional arrays (2x2, 3x2, and 2x3) 
# each in its own codeblock, and print them to the screen.

NumPy will try to guess the datatype (dtype) of your data based on what you've given it.

In [6]:
x = np.array([[4,5],[9,8]])
x.dtype

dtype('int32')

In [ ]:
# Play along!  What is the dtype of this numpy array?
x = np.array([[3.,2.,1.234,1.134]])

You can also specify these directly using an ARGUMENT.  Arguments are often options that you pass a function, to control or specify how you want the input to be processed.

In [8]:
# "dtype=float" is the argument
x = np.array([3,4,5],dtype=float)
x.dtype

dtype('float64')

In [3]:
# Play along!  Add an argument to make this array a "float"
x = np.array([9,9,1])
x.dtype

dtype('int32')

There are many built-in functions to rapidly create arrays.  

Making an array of zeros or ones is actually quite common.

Note that the first digit specifies rows, the second, columns.

These functions take a tuple of values (note the double parentheses).

In [15]:
x = np.ones((3,2))
y = np.zeros((2,4))
x

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [ ]:
# Play along!  Make an array of zeros with 3 rows, and 5 columns.

## arange
<font color="red">arange</font> is the numpy equivalent of <font color="red">range</font>, and follows the same syntax.

arange(start,stop*,step)

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Play along!
# 1) Make a range of ints from 9 to 14
# 2) Make a range of ints from 9 to 2
# 3) Make a range of ints from 0 to 20 by twos

Unlike range, however, arange can make arrays of floats.  Just use decimal values!

In [17]:
x = np.arange(0,2,.1)
x

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9])

Notice that like range, arange goes up to BUT NOT INCLUDING your stop number.  So the example below stops at 1.9 (2 - .1, or the STOP minus the STEP).

In [ ]:
# Play along!  Make five arrays of floats using arange.
# Play with start, stop, and step values.

## linspace

<font color="red">linspace</font> is similar, but you specify the start and stop you want, and how many total numbers you want, and it calculates the step.  The step will be (max-min)/(n-1).

linspace(start,stop,n)

In [4]:
x = np.linspace(0,1,5)
x

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [6]:
# Notice that the length of the array will be equal to the n argument
x = np.linspace(0,1,5)
len(x)

5

In [7]:
# Play along!  Generate five numpy arrays using linspace.

## random.rand
You can also generate random arrays, which is the foundation of a lot of useful things we're going to be able to do with numpy.  There are a number of different ways to generate random numbers.  Here is one.

In [21]:
# Create a 3x4 2D array of random numbers between 0 and 1
x = np.random.rand(3,4)
x

array([[ 0.19121998,  0.352247  ,  0.36033605,  0.2895004 ],
       [ 0.49985407,  0.04560765,  0.76280707,  0.14996935],
       [ 0.09980621,  0.80035125,  0.6930038 ,  0.4098617 ]])

In [45]:
# You can scale the random numbers by doing some multiplication:
a = np.random.rand(10)  # This creates random numbers between 0 and 1
b = 10 * a; # This creates random numbers between 0 and 10!
print(a)
print(b)

[ 0.98189064  0.48645609  0.74153724  0.91755167  0.09277096  0.6107545
  0.03536151  0.73827891  0.65802432  0.90529108]
[ 9.8189064   4.86456089  7.41537235  9.17551667  0.92770957  6.10754501
  0.35361509  7.38278906  6.58024316  9.05291081]


In [ ]:
# Play along!
# Create 10 random numbers between 0 and 100

In [46]:
# You can use addition to move the range.  If I want to create random numbers 
# between 2 and 5, I can do this:
x = 3*np.random.rand(10) + 2
print(x)

# The 3 at the beginning is the range (5-2) and the 2 at the end is the start
# point

[ 2.3623881   2.36485533  3.15091238  2.61022703  2.61150257  3.39692562
  3.71383696  2.94140145  2.28348375  2.85574432]


In [ ]:
# Play along!  
# Create 10 random numbers between 9 and 33


In [ ]:
# Play along!  Make a 2D array of random numbers between 3 and 7

And arrays can be <font color="red">reshaped</font>.

(Note the order after reshaping!)

In [22]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [23]:
x.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
# The number of elements has to be the same for this to work:
x = np.arange(6)
x.reshape(3,3)

ValueError: total size of new array must be unchanged

In [9]:
# Play along!  How many ways can you reshape this array?
x = np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

Each array will have a <font color="red">transpose</font> method, or you can call the transpose function.  

In a transposition, rows become columns, and columns become rows.

In [24]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
x.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [26]:
np.transpose(x)

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [ ]:
# Play along!  
# Create a 5 x 5 array OTHER than the one you see above (0 to 24) and 
# transpose it using both methods.

## Random integers
The random toolkit has a number of different ways to create random numbers.  Here's another one that creates random integers.

In [102]:
x = np.random.randint(-1,60,(2,10))
x

array([[17, 11,  9,  7, 50, 29, 50, 41, 52, 29],
       [41, 38,  4, 55, 44, 51,  7, 29, 22, 29]])

In [ ]:
# Play along!  randint took three pieces of information, or arguments.
# Identify each one in the example above, and write a sentence or two saying
# what it does.  Feel free to look at the documentation to help you!

In [ ]:
# Play along!  Modify the example above to:
# 1) Make 10 random numbers between 55 and 75
# 2) Make 20 random numbers between 1 and 5
# 3) Make a 2D array (3x3) of numbers between 0 and 1 (inclusive)

# Numpy arithmetic
You can use basic operations on these arrays as if they were single values.

It is this feature that makes NumPy extremely useful for image analysis and manipulation.

In [13]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [32]:
a - b

array([20, 29, 38, 47])

In [33]:
b**2

array([0, 1, 4, 9])

In [17]:
# Play along!  Create two, 2D arrays of size 3x3, and demonstrate 
# addition, subtraction, multiplication, division, mod, and exponent operations


In [47]:
# Another really nice feature of numpy arrays is that you can add, subtract
# a single value from the array, and it BROADCASTS that value so that ALL
# elements are processed:

a = np.arange(10)
print(a)
b = a - 5
print(b)

[0 1 2 3 4 5 6 7 8 9]
[-5 -4 -3 -2 -1  0  1  2  3  4]


In [107]:
# Other operations work in the same way: You can test whether
# ALL elements in an array match a given condition:
b = np.arange(6)
print(b)
c = b <= 2
print(c)
print(c.dtype)

[0 1 2 3 4 5]
[ True  True  True False False False]
bool


In [24]:
# And variable assignment works in the same way
a = np.linspace(10,20,5)
b = np.arange(5)
c = a - b

In [27]:
# You can do multiple comparisons, but you need to group with parentheses
# and using the & symbol instead of the word "and", | instead of "or", and !
# instead of "not".

a = np.linspace(10,20,5)
d = (a < 12) | (a > 17)
print(a)
print(d)

[ 10.   12.5  15.   17.5  20. ]
[ True False False  True  True]


In [ ]:
# Play along!
# Create an array with linspace, and do several multiple comparisons using 
# &, |, and !


In [38]:
# These evaluations can then be used to index an array

# Which numbers between 0 and 9999 are divisible by 33?
a = np.arange(10**3)
b = a % 33 == 0
print(a[b])

[  0  33  66  99 132 165 198 231 264 297 330 363 396 429 462 495 528 561
 594 627 660 693 726 759 792 825 858 891 924 957 990]


In [114]:
# This is what the above would look like in straight Python
b = []
for num in range(10**3):
    if num % 33 == 0:
        b.append(num)
print(b)

[0, 33, 66, 99, 132, 165, 198, 231, 264, 297, 330, 363, 396, 429, 462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825, 858, 891, 924, 957, 990]


In [37]:
# As these make more sense, you can combine many of these operations:
x = np.arange(10**3)
print(x[x%33==0])

[  0  33  66  99 132 165 198 231 264 297 330 363 396 429 462 495 528 561
 594 627 660 693 726 759 792 825 858 891 924 957 990]


In [ ]:
# Play along!
# How many numbers between 1000 and 9987 are divisible by 13?

## Array methods
When you create an array, you're create an <font color="red">object</font> that has <font color="red">methods</font> that you can use.  We've already seen one of these with transpose, but there are many others.

In [39]:
a = np.random.rand(3,3)
a

array([[ 0.13342821,  0.08442359,  0.34160388],
       [ 0.06745702,  0.52773459,  0.56424101],
       [ 0.79688274,  0.38595253,  0.86470818]])

In [40]:
a.max()

0.86470818352709344

In [37]:
a.min()

0.046228352579102405

In [38]:
a.sum()

4.3630842583371905

In [41]:
a = np.random.randint(0,10,(3,3))
a

array([[8, 7, 8],
       [0, 2, 0],
       [3, 3, 0]])

In [42]:
np.sqrt(a)

array([[ 2.64575131,  2.82842712,  2.82842712],
       [ 2.82842712,  0.        ,  0.        ],
       [ 3.        ,  2.44948974,  2.23606798]])

In [43]:
# Play along!  Create an array and use the methods above to find maximum,
# minimum, square root, mean, and sum of all the numbers
a = np.random.rand(10,10)
a.mean()

0.50009468045172156

In [ ]:
# Play along
# Create an array (A) of random numbers, 100x100.  Then create a second array (B)
# That is the difference between A and the mean of array A.

## Slicing

One dimensional arrays use standard list syntax for slicing.  

But, you can also make assignments with NumPy, something not possible with standard lists.

In [43]:
a = np.arange(3,9)
a

array([3, 4, 5, 6, 7, 8])

In [44]:
a[2]

5

In [45]:
a[2:]

array([5, 6, 7, 8])

In [49]:
# The above is standard python.  This is new:
a = np.arange(3,9)
print(a)
a[2:] = 0
print(a)

[3 4 5 6 7 8]
[3 4 0 0 0 0]


In [ ]:
# Play along! 

A = np.zeros(10)

# Set elements 2 to 5 as 3

# Set elements 7 to the end as 10 using negative indices

# Print the array

In [61]:
# You can make multiple assignments, too:

a = np.arange(10)
print(a)
indices = np.array((1,5,9))
a[indices] = np.array([9,99,999])
print(a)

[0 1 2 3 4 5 6 7 8 9]
[  0   9   2   3   4  99   6   7   8 999]


## Two dimensional slicing

Two dimensional slicing works the same as other slicing, but you put a comma to separate the dimensions: 
array(row,col)

In [63]:
## Two dimensional slicing
a = np.arange(9).reshape(3,3).T
a

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [64]:
# Grab row 2, column 2
a[2,2]

8

In [65]:
# Grab row 0, column 2
a[0,2]

6

In [66]:
# Grab from row 1 down, and col 1 over
a[1:,1:]

array([[4, 7],
       [5, 8]])

In [ ]:
# Play along!  Create a 2D array and experiment with 2D slicing syntax.  
# Show me at least 5 slices

## 3D Arrays

Numpy can make arrays of any dimension!  We don't usually use more than four.

What does a 3D array look like?

In [3]:
# This will make an array of two layers, 3 rows, and 4 columns
# Note the difference in order!  This is just a convention; your arrays have
# no "orientation".

a = np.arange(24)
a = a.reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# Play along!  Make a 3D array using arange and reshape, and another one using 
# a random number generator.  Print them to the screen.

## Stacking arrays

Arrays can be stacked.  Both hstack and vstack take a single argument - a tuple of the things you want stacked.

In [5]:
# This will make a two 2x2 arrays, and stack them one next to the other.
= np.ones((2,2))
b = np.zeros((2,2))
np.hstack((a,b))

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

In [6]:
# You can also stack one on top of the other (vertical stack)
np.vstack((a,b))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [ ]:
# Play along!  Make two arrays, and stack them vertically and horizontally.

## Shape is like len(), but multidimensional
Use shape to see how many elements are in each dimension.

len(shape) will tell you how many dimensions are there.

Be careful – there’s a difference between an nx1 array and an array with n elements.  

nx1 is a 2D array, n is a 1D array.

In [8]:
a = np.ones((3,2))
np.shape(a)

(3, 2)

In [9]:
# Notice on this one that there is no second item!
# This is different than 10x1, or 1x10!
np.shape(np.arange(10))

(10,)

In [11]:
np.shape(np.ones((3,1)))

(3, 1)

In [12]:
np.shape(np.ones((3)))

(3,)

The shape of an array is important for how an array will look when stacked.  Compare the 1D and 2D cases.

The 1D Case:

In [15]:
# a and b are ONE dimensional
a = np.zeros(5)
b = np.ones(5)
np.hstack((a,b))

array([ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Play along!  In your own words what happened when you hstacked 
# these one dimensional arrays?

In [16]:
np.vstack((a,b))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [ ]:
# Play along!  What happened when you vstacked them?

The 2D case:

In [67]:
# These are two dimensional, five rows by 1 column
a = np.zeros((5,1))
b = np.ones((5,1))
np.hstack((a,b))

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]])

In [ ]:
# Play along!  How was this different than the 1D hstack above?

In [20]:
np.vstack((a,b))

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [68]:
# Play along!  How was this different than the 1D vstack above?

## Splits
Just like arrays can be stacked, they can be split.

In [71]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
print("The array:")
a = np.arange(16).reshape(4,4)
print(a)
split = np.hsplit(a,2)  # Split into 2 pieces

print("First piece:")
print(split[0])  # Print the first piece

print("Second piece:")
print(split[1])  # Print the second piece

The array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
First piece:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Second piece:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [29]:
np.vsplit(a,3)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]])]

In [ ]:
# Play along!
# Make an array, and split it horizontally and vertically.

## Working with objects
Like most other objects, the equal operator acts as a pointer.
It does not make a new copy.  It is the same object.

In [30]:
a = np.random.rand(3,3)
a

array([[ 0.14230199,  0.47248797,  0.45838951],
       [ 0.2133348 ,  0.64658308,  0.35421195],
       [ 0.39479566,  0.34656975,  0.99984953]])

In [32]:
b = a
b[0,0] = 0
a

array([[ 0.        ,  0.47248797,  0.45838951],
       [ 0.2133348 ,  0.64658308,  0.35421195],
       [ 0.39479566,  0.34656975,  0.99984953]])

You can use copy explicitly if you want to make a copy.

In [33]:
a = np.random.rand(3,3)
b = a.copy()
b[0,0] = 0
a

array([[ 0.33306455,  0.43828155,  0.03754708],
       [ 0.11524337,  0.167559  ,  0.55141816],
       [ 0.41367894,  0.62089992,  0.82829506]])

In [ ]:
# Play along!
# Make an array (A), then set B = A.  Modify A and demonstrate that B 
# is also modified.